### ISSUE TITLE
Service chapters on,/off

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/generate-release-notes#101]
## Background
Crwating draft cliser to desired final state

## Feature
Make it possible to switch on/off not just all service chapters as a group, but one by one.

## Proposed Solution
Solution Ideas:
1. Setting `show-service-chapters` -> boolean, default `true`
2. Setting `show-service-chapter1`-> boolean, default `show-service-chapters`
3. Setting `show-service-chapter2`-> boolean, default `show-service-chapters
4. ...

**Comment by miroslavpojer** [comment]
## Background
Service chapters help identify quality gaps in release metadata (missing PRs, unlabeled issues, direct commits, etc.). Currently, the `warnings` input controls all service chapters as a single group—either all are shown or all are hidden. 

For cleaner release notes drafts, users need the ability to selectively show/hide individual service chapters while keeping others visible. 

## Problem Statement
The current `warnings: true/false` setting is too coarse-grained. Users cannot: 
- Hide specific diagnostic chapters that are irrelevant to their workflow
- Keep only the service chapters that matter for their release quality checks
- Gradually adopt service chapters without overwhelming contributors

## Proposed Solution

Add a new input `hidden-service-chapters` that accepts a list of service chapter titles to hide:

```yaml
inputs:
  warnings:
    description: 'Enable service chapters (master toggle).'
    required: false
    default: 'true'
  
  hidden-service-chapters: 
    description: |
      List of service chapter titles to hide from output (comma or newline separated).
      Title matching is exact and case-sensitive.
      Example: "Direct Commits ⚠️, Others - No Topic ⚠️"
      Available service chapters: 
      - "Closed Issues without Pull Request ⚠️"
      - "Closed Issues without User Defined Labels ⚠️"
      - "Merged PRs without Issue and User Defined Labels ⚠️"
      - "Closed PRs without Issue and User Defined Labels ⚠️"
      - "Merged PRs Linked to 'Not Closed' Issue ⚠️"
      - "Direct Commits ⚠️"
      - "Others - No Topic ⚠️"
    required: false
    default: ''
```

### Logic
- If `warnings:  false`, no service chapters are shown (master override, existing behavior)
- If `warnings: true`, show all service chapters except those listed in `hidden-service-chapters`
- When `hidden-service-chapters` is empty/unset, all service chapters are visible (existing behavior)

### Example Usage

**Example 1: Hide specific diagnostic chapters**
```yaml
- name: Generate Release Notes
  uses: AbsaOSS/generate-release-notes@v1
  env:
    GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
  with:
    tag-name: "v2.0.0"
    chapters:  |
      - {"title": "New Features 🎉", "labels": ["feature"]}
      - {"title":  "Bugfixes 🛠", "labels": ["bug"]}
    warnings: true
    hidden-service-chapters:  |
      Direct Commits ⚠️
      Others - No Topic ⚠️
```

**Example 2: Show only specific service chapters**
```yaml
- name: Generate Release Notes
  uses: AbsaOSS/generate-release-notes@v1
  with:
    tag-name: "v2.0.0"
    warnings: true
    # Hide all except "Closed Issues without Pull Request"
    hidden-service-chapters:  |
      Closed Issues without User Defined Labels ⚠️
      Merged PRs without Issue and User Defined Labels ⚠️
      Closed PRs without Issue and User Defined Labels ⚠️
      Merged PRs Linked to 'Not Closed' Issue ⚠️
      Direct Commits ⚠️
      Others - No Topic ⚠️
```

**Example 3: Comma-separated format**
```yaml
- name: Generate Release Notes
  uses: AbsaOSS/generate-release-notes@v1
  with:
    tag-name:  "v2.0.0"
    warnings: true
    hidden-service-chapters: "Direct Commits ⚠️, Others - No Topic ⚠️"
```

---

## Service Chapters Reference

The following service chapters are currently defined in the codebase:

| Chapter Title | Constant Name | Condition Reported |
|---------------|---------------|-------------------|
| **Closed Issues without Pull Request ⚠️** | `CLOSED_ISSUES_WITHOUT_PULL_REQUESTS` | Closed issues with zero linked PRs |
| **Closed Issues without User Defined Labels ⚠️** | `CLOSED_ISSUES_WITHOUT_USER_DEFINED_LABELS` | Closed issues missing all user-defined chapter labels |
| **Merged PRs without Issue and User Defined Labels ⚠️** | `MERGED_PRS_WITHOUT_ISSUE_AND_USER_DEFINED_LABELS` | Merged PRs with no linked issue and none of the user-defined labels |
| **Closed PRs without Issue and User Defined Labels ⚠️** | `CLOSED_PRS_WITHOUT_ISSUE_AND_USER_DEFINED_LABELS` | Closed (not merged) PRs missing issue link and user-defined labels |
| **Merged PRs Linked to 'Not Closed' Issue ⚠️** | `MERGED_PRS_LINKED_TO_NOT_CLOSED_ISSUES` | PRs merged while a linked issue is still open |
| **Direct Commits ⚠️** | `DIRECT_COMMITS` | Commits on default branch without a PR |
| **Others - No Topic ⚠️** | `OTHERS_NO_TOPIC` | Fallback bucket when none of the above matched |

> **Note:** Ensure titles include the ⚠️ emoji when specifying in `hidden-service-chapters`

---

## Behavior Specification

### Title Matching Rules
- **Exact matching:** Chapter title must match exactly (case-sensitive)
- **Whitespace handling:** Leading and trailing whitespace is trimmed from input tokens
- **Emoji support:** Titles include the ⚠️ emoji (must be included in hidden list)
- **Invalid titles:** Unknown chapter titles log a warning but don't break execution

### Input Parsing
- **Separators:** Both newline and comma are supported as separators
- **Mixed separators:** Can mix newlines and commas (newlines processed first, then commas)
- **Deduplication:** Duplicate titles in the list are automatically deduplicated
- **Empty input:** When empty/unset, all service chapters are visible

### Interaction with Other Settings
- **`warnings:  false`** → All service chapters hidden (master override, ignores `hidden-service-chapters`)
- **`warnings: true`** → Show all except those in `hidden-service-chapters`
- **`print-empty-chapters`** → Still respected for non-hidden service chapters
- **`duplicity-scope`** → Duplicity rules still apply to visible service chapters

---

## Acceptance Criteria

### Functional Requirements
- [ ] Users can specify a list of service chapter titles to hide via `hidden-service-chapters` input
- [ ] Hidden chapters are not rendered in the final release notes output
- [ ] Title matching is exact and case-sensitive (including ⚠️ emoji)
- [ ] Whitespace is trimmed from both input tokens and chapter titles before comparison
- [ ] Both comma and newline separators are supported (and can be mixed)
- [ ] Invalid/unknown chapter titles in the list are logged as warnings but don't break execution
- [ ] The `warnings` input continues to work as a master toggle (overrides `hidden-service-chapters`)
- [ ] When `hidden-service-chapters` is empty/unset, behavior is identical to current implementation

### Quality Requirements
- [ ] Backward compatibility: existing workflows using only `warnings` behave identically
- [ ] Performance:  hiding chapters doesn't significantly impact processing time
- [ ] Error handling: graceful degradation for malformed input
- [ ] Logging: clear info/warning messages for hidden chapters and invalid titles

### Documentation Requirements
- [ ] Documentation updated in `docs/features/service_chapters. md`
- [ ] Configuration reference updated with new input
- [ ] Examples added showing different use cases
- [ ] List of exact chapter titles documented (with emoji)

### Testing Requirements
- [ ] Unit tests cover: 
  - Hiding single service chapter
  - Hiding multiple service chapters
  - Exact title matching (case-sensitive)
  - Whitespace handling (leading/trailing spaces)
  - Newline-separated input parsing
  - Comma-separated input parsing
  - Mixed separator input parsing
  - Deduplication of duplicate titles
  - Warning logs for unknown chapter titles
  - Empty input (no chapters hidden)
  - All chapters hidden
  - Emoji handling in titles
  - Master toggle override (`warnings: false`)
- [ ] Integration tests validate:
  - Output with hidden service chapters omitted
  - Visible chapters still render correctly
  - Interaction with `print-empty-chapters`
  - Interaction with `duplicity-scope`
  - Backward compatibility (no `hidden-service-chapters` input)

---

## Related
- Relates to #102 (hiding user-defined chapters)
- See `release_notes_generator/chapters/service_chapters.py` (lines 29-51 for constants, lines 60-99 for initialization)
- See `release_notes_generator/utils/constants.py` for chapter title constants
- See `action.yml` (line 52) for current `warnings` input
- See `docs/features/service_chapters.md` for documentation

---

## Implementation Tasks

### Phase 1: Design & Planning
- [ ] Verify exact chapter title strings from constants
- [ ] Design input parsing strategy (reuse `_normalize_labels` from custom_chapters. py)
- [ ] Design title matching strategy
- [ ] Define warning message format

### Phase 2: Input & Configuration
- [ ] Add `hidden-service-chapters` input to `action.yml`
- [ ] Update `ActionInputs` class in `release_notes_generator/action_inputs.py`:
  - [ ] Add `INPUT_HIDDEN_SERVICE_CHAPTERS` environment variable constant
  - [ ] Add `get_hidden_service_chapters()` static method
  - [ ] Implement parsing logic (newline + comma separation, whitespace trimming)
  - [ ] Add validation and logging

### Phase 3: Core Logic Implementation
- [ ] Update `ServiceChapters` class in `release_notes_generator/chapters/service_chapters. py`:
  - [ ] Add `hidden_chapter_titles` attribute to `__init__()`
  - [ ] Load hidden chapters from `ActionInputs.get_hidden_service_chapters()`
  - [ ] Update `to_string()` method to filter out hidden chapters
  - [ ] Add validation:  warn for titles not matching known service chapters
  - [ ] Add info logging:  which chapters are hidden
  - [ ] Ensure hidden chapters are skipped before any rendering logic

### Phase 4: Validation & Logging
- [ ] Implement title validation: 
  - [ ] Compare against known service chapter title constants
  - [ ] Log warning for unknown titles with suggestion for valid titles
  - [ ] Continue execution (don't fail on unknown titles)
- [ ] Add logging: 
  - [ ] Info: "Hiding service chapter:  {title}"
  - [ ] Warning: "Unknown service chapter title in hidden list:  {title}. Available titles: ..."
  - [ ] Debug: List of hidden chapter titles parsed from input

### Phase 5: Testing
- [ ] Unit tests for `ActionInputs.get_hidden_service_chapters()`:
  - [ ] Empty input returns empty list
  - [ ] Single title (newline format)
  - [ ] Multiple titles (newline format)
  - [ ] Multiple titles (comma format)
  - [ ] Mixed separators
  - [ ] Whitespace handling
  - [ ] Deduplication
- [ ] Unit tests for `ServiceChapters.to_string()`:
  - [ ] No hidden chapters (existing behavior)
  - [ ] Hide single chapter
  - [ ] Hide multiple chapters
  - [ ] Hide all chapters
  - [ ] Unknown title in list (warning logged)
  - [ ] Master toggle override (`warnings: false`)
- [ ] Integration tests:
  - [ ] End-to-end with hidden service chapters
  - [ ] Verify hidden chapters omitted from output
  - [ ] Verify visible chapters render correctly
  - [ ] Test with various `print-empty-chapters` values
  - [ ] Test with various `duplicity-scope` values
- [ ] Backward compatibility tests:
  - [ ] Existing workflows without `hidden-service-chapters` produce identical output

### Phase 6: Documentation
- [ ] Update `docs/features/service_chapters.md`:
  - [ ] Add "Hiding Individual Service Chapters" section
  - [ ] Include complete list of chapter titles (with emoji)
  - [ ] Add examples (newline, comma, mixed)
  - [ ] Document title matching rules
  - [ ] Document interaction with `warnings`
- [ ] Update `README.md`:
  - [ ] Add example in features section
- [ ] Update configuration reference documentation
- [ ] Add inline code documentation (docstrings)

### Phase 7: Review & Release
- [ ] Code review
- [ ] Manual testing with real repository
- [ ] Update CHANGELOG
- [ ] Prepare release notes

---

## Technical Implementation Notes

### Title Constants Mapping
Map user input titles to internal constants for validation: 

```python
# In service_chapters.py or constants.py
SERVICE_CHAPTER_TITLES = {
    CLOSED_ISSUES_WITHOUT_PULL_REQUESTS: "Closed Issues without Pull Request ⚠️",
    CLOSED_ISSUES_WITHOUT_USER_DEFINED_LABELS: "Closed Issues without User Defined Labels ⚠️",
    MERGED_PRS_WITHOUT_ISSUE_AND_USER_DEFINED_LABELS: "Merged PRs without Issue and User Defined Labels ⚠️",
    CLOSED_PRS_WITHOUT_ISSUE_AND_USER_DEFINED_LABELS: "Closed PRs without Issue and User Defined Labels ⚠️",
    MERGED_PRS_LINKED_TO_NOT_CLOSED_ISSUES: "Merged PRs Linked to 'Not Closed' Issue ⚠️",
    DIRECT_COMMITS: "Direct Commits ⚠️",
    OTHERS_NO_TOPIC: "Others - No Topic ⚠️",
}
```

### Parsing Logic (Reuse Pattern from Custom Chapters)
```python
# In ActionInputs class
@staticmethod
def get_hidden_service_chapters() -> list[str]:
    """Parse hidden-service-chapters input into list of titles."""
    raw_input = os.getenv("INPUT_HIDDEN_SERVICE_CHAPTERS", "")
    
    if not raw_input or not raw_input.strip():
        return []
    
    # Reuse _normalize_labels pattern from custom_chapters.py
    titles = []
    seen = set()
    
    # Process newlines first, then commas
    for line in raw_input.splitlines():
        for token in line.split(","):
            title = token.strip()
            if title and title not in seen: 
                titles.append(title)
                seen.add(title)
    
    return titles
```

### Filtering Logic in ServiceChapters
```python
# In ServiceChapters. to_string()
def to_string(self) -> str:
    """Generate string representation of service chapters."""
    output = ""
    
    for chapter_constant, chapter in self.chapters.items():
        chapter_title = SERVICE_CHAPTER_TITLES.get(chapter_constant, chapter. title)
        
        # Skip hidden chapters
        if chapter_title in self.hidden_chapter_titles:
            logger.info(f"Skipping hidden service chapter: {chapter_title}")
            continue
        
        # ...  existing rendering logic ...
    
    return output
```

### Validation Logic
```python
# In ServiceChapters.__init__() or as separate method
def _validate_hidden_chapters(self):
    """Validate hidden chapter titles and log warnings for unknown titles."""
    valid_titles = set(SERVICE_CHAPTER_TITLES. values())
    
    for title in self.hidden_chapter_titles:
        if title not in valid_titles:
            logger.warning(
                f"Unknown service chapter title in hidden list: '{title}'. "
                f"Available titles: {', '.join(sorted(valid_titles))}"
            )
```

---

## Edge Cases to Handle

| Edge Case | Expected Behavior |
|-----------|------------------|
| `warnings: false` + `hidden-service-chapters:  "..."` | Master toggle wins:  all hidden (ignore `hidden-service-chapters`) |
| All service chapters hidden | Empty service chapters section in output |
| Hidden chapter title with typo | Log warning, continue with valid titles |
| Duplicate titles in input | Deduplicate silently |
| Empty `hidden-service-chapters` | All service chapters visible (existing behavior) |
| Title without emoji | Won't match (log warning), chapter remains visible |
| Title with wrong case | Won't match (log warning), chapter remains visible |
| Mixed newlines and commas | Parse both correctly |
| Leading/trailing whitespace | Trim and match correctly |

---

## Migration Guide for Users

### Before (Current Behavior)
```yaml
# All or nothing control
warnings: true   # Show all service chapters
# OR
warnings: false  # Hide all service chapters
```

### After (New Granular Control)
```yaml
# Show all service chapters (same as before)
warnings: true

# Show all except specific chapters (NEW)
warnings: true
hidden-service-chapters: "Direct Commits ⚠️, Others - No Topic ⚠️"

# Hide all (same as before)
warnings: false
```

### Backward Compatibility
- Existing workflows using only `warnings` → **No changes needed, identical behavior**
- New workflows → Can optionally add `hidden-service-chapters` for granular control
